version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Qdrant__Url=http://qdrant:6333
      - HuggingFace__ApiKey=${HUGGINGFACE_API_KEY}
    depends_on:
      - qdrant
    networks:
      - app-network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6334:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - app-network

volumes:
  qdrant_data:

networks:
  app-network:
    driver: bridge